### ISSUE TITLE
Devices not showing up in AndroidDrive even though they show up in ADB

### ISSUE THREAD

**Issue by kirpeace121** [Gustav-Lindberg/AndroidDrive#1]
it is not detecting my realme xt device. I have enabled usb debugging and developer options

**Comment by Gustav-Lindberg** [comment]
Right click on the AndroidDrive icon in the taskbar and click on Devices:

<img width="170" src="https://user-images.githubusercontent.com/95423695/156880080-13f9b30c-8a26-48d6-8e21-14b0c5bbbe46.png">

Then it should open a list of devices. Does your device show up in the list?

If it does, click on it. If the button on the bottom left says "Connecting...", you just need to wait. If it says "Connect drive", click on it. If it says "Disconnect drive", the drive should show up in This PC.

If it doesn't show up in the list, run open `C:\Windows\System32\cmd.exe` and type the commands below, replacing `C:\Path\to\AndroidDrive` with the path to the folder where you installed AndroidDrive. What is the output?

```
cd "C:\Path\to\AndroidDrive"
adb devices
```

**Comment by anmac1789** [comment]
I have tried your above method in post #2, 2 of my android devices are not showing up also. They are a galaxy s8 and LG G3. Both have debugging options enabled. I am on windows 10 x64 enterprise. I ran your adb devices code and it shows that both of my phones are connected to the PC with their serial number.

**Comment by Gustav-Lindberg** [comment]
@anmac1789 To figure out what's wrong, follow these steps:

1. If AndroidDrive is running, close it by right clicking on the AndroidDrive icon in the task bar and clicking on Exit.
2. Plug in your Android device that's not being detected.
3. Download and unzip [AndroidDriveDebug.zip](https://github.com/Gustav-Lindberg/AndroidDrive/files/8488021/AndroidDriveDebug.zip), which contains a debug version of AndroidDrive, and run the  AndroidDrive.exe file that's in there.
4. A console window should appear. When something has been written to that console window, send me a screenshot of it.

**Comment by anmac1789** [comment]
> @anmac1789 To figure out what's wrong, follow these steps:
> 
> 1. If AndroidDrive is running, close it by right clicking on the AndroidDrive icon in the task bar and clicking on Exit.
> 2. Plug in your Android device that's not being detected.
> 3. Download and unzip [AndroidDriveDebug.zip](https://github.com/Gustav-Lindberg/AndroidDrive/files/8488021/AndroidDriveDebug.zip), which contains a debug version of AndroidDrive, and run the  AndroidDrive.exe file that's in there.
> 4. A console window should appear. When something has been written to that console window, send me a screenshot of it.

![debug window](https://user-images.githubusercontent.com/103609429/163359259-d0a0be71-6cf8-4ee4-9b56-6026295b1fdb.png)

**Comment by Gustav-Lindberg** [comment]
@anmac1789 It should be fixed now. You can download the latest version [here](https://github.com/Gustav-Lindberg/AndroidDrive/raw/main/AndroidDrive.zip).
